development:
  twitter:
    consumer_key: 'PVRb6364NiQ36APEupets0HTK'
    consumer_secret: 'nxzI19el8FzuGm3jANNyKIHukG2qyU8I6GxUVXNGjXFN6r4DwR'

qa:
  twitter:
    consumer_key: 'PVRb6364NiQ36APEupets0HTK'
    consumer_secret: 'nxzI19el8FzuGm3jANNyKIHukG2qyU8I6GxUVXNGjXFN6r4DwR'

test:
  twitter:
    consumer_key: 'PVRb6364NiQ36APEupets0HTK'
    consumer_secret: 'nxzI19el8FzuGm3jANNyKIHukG2qyU8I6GxUVXNGjXFN6r4DwR'

production:
  twitter:
    consumer_key: 'PVRb6364NiQ36APEupets0HTK'
    consumer_secret: 'nxzI19el8FzuGm3jANNyKIHukG2qyU8I6GxUVXNGjXFN6r4DwR'

