development:
  adapter: postgresql
  database: favourite_tweets_development
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  database: favourite_tweets_test
  username: postgres
  password: postgres
  host: localhost