require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SynchronizationsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Synchronization. As you add validations to Synchronization, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SynchronizationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all synchronizations as @synchronizations" do
      synchronization = Synchronization.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:synchronizations)).to eq([synchronization])
    end
  end

  describe "GET show" do
    it "assigns the requested synchronization as @synchronization" do
      synchronization = Synchronization.create! valid_attributes
      get :show, {:id => synchronization.to_param}, valid_session
      expect(assigns(:synchronization)).to eq(synchronization)
    end
  end

  describe "GET new" do
    it "assigns a new synchronization as @synchronization" do
      get :new, {}, valid_session
      expect(assigns(:synchronization)).to be_a_new(Synchronization)
    end
  end

  describe "GET edit" do
    it "assigns the requested synchronization as @synchronization" do
      synchronization = Synchronization.create! valid_attributes
      get :edit, {:id => synchronization.to_param}, valid_session
      expect(assigns(:synchronization)).to eq(synchronization)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Synchronization" do
        expect {
          post :create, {:synchronization => valid_attributes}, valid_session
        }.to change(Synchronization, :count).by(1)
      end

      it "assigns a newly created synchronization as @synchronization" do
        post :create, {:synchronization => valid_attributes}, valid_session
        expect(assigns(:synchronization)).to be_a(Synchronization)
        expect(assigns(:synchronization)).to be_persisted
      end

      it "redirects to the created synchronization" do
        post :create, {:synchronization => valid_attributes}, valid_session
        expect(response).to redirect_to(Synchronization.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved synchronization as @synchronization" do
        post :create, {:synchronization => invalid_attributes}, valid_session
        expect(assigns(:synchronization)).to be_a_new(Synchronization)
      end

      it "re-renders the 'new' template" do
        post :create, {:synchronization => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested synchronization" do
        synchronization = Synchronization.create! valid_attributes
        put :update, {:id => synchronization.to_param, :synchronization => new_attributes}, valid_session
        synchronization.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested synchronization as @synchronization" do
        synchronization = Synchronization.create! valid_attributes
        put :update, {:id => synchronization.to_param, :synchronization => valid_attributes}, valid_session
        expect(assigns(:synchronization)).to eq(synchronization)
      end

      it "redirects to the synchronization" do
        synchronization = Synchronization.create! valid_attributes
        put :update, {:id => synchronization.to_param, :synchronization => valid_attributes}, valid_session
        expect(response).to redirect_to(synchronization)
      end
    end

    describe "with invalid params" do
      it "assigns the synchronization as @synchronization" do
        synchronization = Synchronization.create! valid_attributes
        put :update, {:id => synchronization.to_param, :synchronization => invalid_attributes}, valid_session
        expect(assigns(:synchronization)).to eq(synchronization)
      end

      it "re-renders the 'edit' template" do
        synchronization = Synchronization.create! valid_attributes
        put :update, {:id => synchronization.to_param, :synchronization => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested synchronization" do
      synchronization = Synchronization.create! valid_attributes
      expect {
        delete :destroy, {:id => synchronization.to_param}, valid_session
      }.to change(Synchronization, :count).by(-1)
    end

    it "redirects to the synchronizations list" do
      synchronization = Synchronization.create! valid_attributes
      delete :destroy, {:id => synchronization.to_param}, valid_session
      expect(response).to redirect_to(synchronizations_url)
    end
  end

end
